// client/src/app/modes/decks/decks.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { DecksService } from './decks.service';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-decks',
  templateUrl: './decks.component.html',
  styleUrl: './decks.component.css',
})
export class DecksComponent implements OnInit {
  decksService = inject(DecksService);
  router = inject(Router);
  activatedRoute = inject(ActivatedRoute);

  decks = this.decksService.allDecks;

  ngOnInit(): void {
    this.decksService.refresh();
  }

  createDeck() {
    this.decksService.createDeck();
  }
}

<section class="decks-container">
  @if (decks().length > 0) { @for (deck of decks(); track deck.deck_id) {
  <app-deck [deck]="deck" />
  } } @else {
  <h1 class="text-white text-center no-decks">No Decks</h1>
  } @if (decks().length < 5) {
  <button
    type="button"
    class="btn btn-dark add-color add-deck pos-rel"
    (click)="createDeck()"
  >
    Add Deck
  </button>
  }
</section>

// client/src/components/authenticated/Decks.tsx
import React from "react";
import Deck from "./Deck";
import { DeckData } from "../../contexts/DeckContext";
import useDeck from "../../hooks/useDeck";
import useDeckService from "../../hooks/services/useDeckService";
const Decks = () => {
  const { decks } = useDeck();
  const { addDeck } = useDeckService();

  const handleDeckCreation = async () => {
    addDeck();
  };

  return (
    <section className="decks-container">
      {decks.length > 0 ? (
        decks.map((deck: DeckData, deck_index) => {
          const { deck_id, deck_name, cards } = deck;
          return (
            <Deck
              key={deck_id}
              deck_index={deck_index}
              deck_id={deck_id}
              deck_name={deck_name}
              cardCount={cards?.length !== null ? cards.length : 0}
            />
          );
        })
      ) : (
        <h1 className="text-white text-center no-decks">No Decks</h1>
      )}

      {decks.length < 5 && (
        <button
          type="button"
          className="btn btn-dark add-color add-deck pos-rel"
          onClick={handleDeckCreation}
        >
          Add Deck
        </button>
      )}
    </section>
  );
};

export default Decks;
