// client/src/components/NotFound.tsx
import React from "react";
import { Link } from "react-router-dom";
import { ROUTE_PREFIX } from "../constants";

const NotFound = () => {
  return (
    <section className="not-found">
      <h1>Not Found</h1>
      <Link className="btn btn-ddark" to={`${ROUTE_PREFIX}/`}>
        To Home
      </Link>
    </section>
  );
};

export default NotFound;

// client/src/app/not-found/not-found.component.ts
import { Component } from "@angular/core";
import { RouterLink } from "@angular/router";

@Component({
  selector: "app-not-found",
  templateUrl: "./not-found.component.html",
  styleUrls: ["./not-found.component.css"],
  imports: [RouterLink],
})
export class NotFoundComponent {}

<section class="not-found">
  <h1>Not Found</h1>
  <button
    class="btn btn-ddark"
    routerLink="/"
    routerLinkActive="router-link-active"
  >
    To Home
  </button>
</section>
