// client/src/components/Login.tsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import useAuthService from "../hooks/services/useAuthService";
import { ROUTE_PREFIX } from "../constants";

export type LoginInfo = {
  email: string;
  password: string;
};

const LOGIN_DATA: LoginInfo = {
  email: "",
  password: "",
};

const Login = () => {
  const { login } = useAuthService();

  const [loginInfo, setLoginInfo] = useState<LoginInfo>(LOGIN_DATA);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { id, value } = e.target;

    setLoginInfo((data) => {
      return {
        ...data,
        [id]: value,
      };
    });
  };

  const handleSubmit = async (e: React.ChangeEvent<HTMLFormElement>) => {
    e.preventDefault();
    await login(loginInfo);
  };

  return (
    <>
      <div className="login-container">
        <form onSubmit={handleSubmit}>
          <label htmlFor="email" className="form-label">
            Email
          </label>
          <input
            id="email"
            type="email"
            className="form-control mb-3"
            placeholder="Email"
            value={loginInfo.email}
            onChange={handleChange}
          />
          <label htmlFor="password" className="form-label">
            Password
          </label>
          <input
            id="password"
            type="password"
            className="form-control mb-2"
            placeholder="Password"
            minLength={10}
            value={loginInfo.password}
            onChange={handleChange}
          />
          <button
            className="btn btn-outline-light w-100 mb-1"
            disabled={!loginInfo.email || !loginInfo.password}
          >
            Login
          </button>
        </form>
        <div className="login-links">
          <Link
            to={`${ROUTE_PREFIX}/register`}
            className="btn btn-link text-decoration-none"
          >
            Register
          </Link>
          <Link to="" className="btn btn-link text-decoration-none">
            Forgot Password
          </Link>
        </div>
      </div>
    </>
  );
};

export default Login;

// client/src/app/login/login.component.ts
import { Component, inject } from '@angular/core';
import { PASSWORD } from '../shared/shared.constants';
import { AuthService } from '../auth/auth.service';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { AlertService } from '../alert/alert.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  alertService = inject(AlertService);
  form = new FormGroup({
    email: new FormControl<string>('', { validators: [Validators.required] }),
    password: new FormControl<string>('', {
      validators: [
        Validators.required,
        Validators.minLength(PASSWORD.PASSWORD_MIN_LENGTH),
      ],
    }),
  });

  constructor(private readonly authService: AuthService) {}

  onSubmit() {
    const { email, password } = this.form.value;
    if (!email || !password) {
      return this.alertService.setAlert('Email or password is empty.');
    }

    this.authService.login({ email, password });
  }
}

<div class="login-container">
  <form (ngSubmit)="onSubmit()" [formGroup]="form">
    <label for="email" class="form-label"> Email </label>
    <input
      id="email"
      name="email"
      type="email"
      class="form-control mb-3"
      placeholder="Email"
      formControlName="email"
    />
    <label for="password" class="form-label"> Password </label>
    <input
      id="password"
      name="password"
      type="password"
      class="form-control mb-2"
      placeholder="Password"
      formControlName="password"
    />
    <button
      type="submit"
      class="btn btn-outline-light w-100 mb-1"
      [disabled]="form.invalid"
    >
      Login
    </button>
  </form>
  <div class="login-links">
    <a
      routerLink="/register"
      routerLinkActive="router-link-active"
      class="btn btn-link text-decoration-none"
    >
      Register
    </a>
    <a class="btn btn-link text-decoration-none"> Forgot Password </a>
  </div>
</div>
