// client/src/app/alert/alert.component.ts
import { Component } from "@angular/core";
import { AlertService } from "./alert.service";

@Component({
  selector: "app-alert",
  templateUrl: "./alert.component.html",
  styleUrls: ["./alert.component.css"],
})
export class AlertComponent {
  constructor(private readonly alertService: AlertService) {}

  get alertType() {
    return this.alertService.alertType;
  }

  get alert() {
    return this.alertService.alert;
  }

  get isAlertActive() {
    return this.alertService.isAlertActive;
  }

  hideAlert() {
    this.alertService.hideAlert();
  }
}

@if (isAlertActive()) {
  <div
    [class]="
      'alert text-center alert-dismissible fade show alert-comp alert-' +
      alertType
    "
    role="alert"
  >
    {{ alert() }}
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
      (click)="hideAlert()"
    ></button>
  </div>
}

// client/src/components/Alert.tsx
import React from "react";
import { useAlert } from "../hooks/useAlert";

const Alert = () => {
  const { alertType, alert, showAlert, hideAlert } = useAlert();
  return (
    <>
      {showAlert && (
        <div
          className={`alert alert-${alertType} text-center alert-dismissible fade show alert-comp`}
          role="alert"
        >
          {alert}
          <button
            type="button"
            className="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
            onClick={hideAlert}
          ></button>
        </div>
      )}
    </>
  );
};

export default Alert;
