// client/src/app/home/home.component.ts
import { Component } from "@angular/core";
import { RouterLink } from "@angular/router";

@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.css"],
  imports: [RouterLink],
})
export class HomeComponent {}

<div class="home-container">
  <h2>Welcome to Rigel</h2>
  <div class="home-btn-container">
    <button
      routerLink="/login"
      routerLinkActive="router-link-active"
      class="btn btn-green"
    >
      Login
    </button>
    <button
      routerLink="/register"
      routerLinkActive="router-link-active"
      class="btn add-color"
    >
      Register
    </button>
  </div>
</div>

// client/src/components/Home.tsx
import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="home-container">
      <h2>Welcome to Rigel</h2>
      <div className="home-btn-container">
        <Link to={"/login"} className="btn btn-green">
          Login
        </Link>
        <Link to={"/register"} className="btn add-color">
          Register
        </Link>
      </div>
    </div>
  );
};

export default Home;
